name = "upfunnel-r2-presign"
main = "r2-presign.js"
compatibility_date = "2024-01-01"

[vars]
R2_BUCKET_NAME = "upfunnel-academy"
R2_ACCESS_KEY_ID = "068c7a59fc24c38689120af3f04458db"
R2_SECRET_ACCESS_KEY = "edb3f8f12faa4f7c5074741388eded5975fdc289c7c22a390382a2ae31f2218b"
R2_ACCOUNT_ID = "1fbed4859cc6f03d691ea813a7039210"
SUPABASE_URL = "https://krtthtzljlyewlngaklo.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_aEHBN2kyCw_nLv06x3UYKg_9dLEVg1p"
